### ISSUE TITLE
Twitter Followers

### ISSUE THREAD

**Issue by AiGreek** [awtrix/awtrix#12]
I can find some things about twitter in the firmware, but nothing done yet ? i'm trying ATM but seems to be harder than youtube ^^'

**Comment by Blueforcer** [comment]
There is nothing about twitter:)
When I find the time, I'll take a look at it. Thanks for your Idea

**Comment by AiGreek** [comment]
Hum, yeah i saw this on the AWTRIXER app (nice app btw) i'm trying the 0.2 Beta but i got some errors after upload

`load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d

csum 0x2d
v4ceabea9
~ld
Settings file not found!
0
Settings file loaded
Failed to parse settings file`

**Comment by Blueforcer** [comment]
Twitter App in todays release
