### ISSUE TITLE
Weather app / dev tree

### ISSUE THREAD

**Issue by nexty5870** [awtrix/awtrix#17]
Dev package came with a new Weather API provider (WUNDERGROUND)

while checking the reason why the weather was not working, I've found that the weather.cpp are still using OWM instead, 

I have input back the "OWM_API_KEY": + Location inside my config.json file and weather is now working again

**Comment by Blueforcer** [comment]
Dev still use Openweathermap. Wonderground is the old provider.

**Comment by Blueforcer** [comment]
My mistake. Openweathermap is the new provider, wonderground the old one. Because i copied a older commit for the dev branch, ive forgot to change the config.json too

**Comment by nexty5870** [comment]
Ok cool just wanted to let you know

Le lun. 16 avr. 2018 à 00:54, Stephan Mühl <notifications@github.com> a
écrit :

**Comment by Blueforcer** [comment]
Thx man. I will fix that

**Comment by Blueforcer** [comment]
thx man.
ive fixed that  
https://github.com/awtrix/awtrix/commit/d0ea560f5e8c2a409cd379fce088a35f7d139412
