### ISSUE TITLE
SYNCING

### ISSUE THREAD

**Issue by LeonDriver** [awtrix/awtrix#21]
Bitte wieder SYNC mit blinkendem N als das SYNCING wo man nicht lesen kann

**Comment by Blueforcer** [comment]
Was kann man daran nicht lesen? 
Das blinkende N war ein bug und wurde gefixed

**Comment by LeonDriver** [comment]
Habe es hinbekommen, SYNC bei BIG TIME funktioniert, allerdings ist unter dem N der Balken an, aber ist erstmal OK.

**Comment by Blueforcer** [comment]
wird im nächsten update ausgeblendet..
