### ISSUE TITLE
Settings "ALEXA" + "SLEEP"

### ISSUE THREAD

**Issue by LeonDriver** [awtrix/awtrix#23]
Ab wann gehen diese funktionen wieder?

**Comment by Blueforcer** [comment]
Alexa eher nicht mehr, da die nötige library viel zu groß ist im Verhältnis zum Nutzen.
Der Sleepmode wird wohl ende der Woche wieder dabei sein, dieser muss nochmal überarbeitet werden

**Comment by LeonDriver** [comment]
Alles klar, dann weiss ich bescheid, danke
