### ISSUE TITLE
BRIGHTNESS 

### ISSUE THREAD

**Issue by DennisXK** [awtrix/awtrix#24]
Stellt man die BRIGHTNESS <=11 werden die Wochentage grün. Weis nicht ob man das in den Griff bekommt, da es eher ein technisches Problem der RGB Led ist. Liegt an den Durchlassspannungen der einzelenen Leds (rot, grün, blau)

**Comment by Blueforcer** [comment]
Frage hast du dir selbst beantwortet:) Blende die wochentage einfach aus wenn du solch eine geringe Helligkeit benötigst
