### ISSUE TITLE
NeoPixel is  a bad choice for the ESP8266

### ISSUE THREAD

**Issue by BigAl66** [awtrix/awtrix#31]
I already made a view other projects with the WS2812b LEDs and the ESP8266 and had very bad expirience with using NeoPixel's library. Also the FastLED library did not work well and reliable on that processor. The only really reliable library I found is the NeoPixelBus by Makuna (github.com/Makuna/NeoPixelBus). The problem is the watchdog of the ESP8266. I wonder a little bit how the AWTRIX can work reliable with the NeoPixel library...

**Comment by Blueforcer** [comment]
"wonder a little bit how the AWTRIX can work reliable with the NeoPixel library" . It works awesome, so why you open an issue for that?
Just because you can't handle it doesn't mean it's a problem for others.
