### ISSUE TITLE
Email notifier

### ISSUE THREAD

**Issue by Blueforcer** [awtrix/awtrix#5]
Showing the number of unread emails

**Comment by AiGreek** [comment]
I think it can be done with a yep/Mqtt/http server and Tasker on Android (same for texts, missed calls ora'ything Android's related(battery, wifi, etc ...) I did a small script about that

**Comment by Blueforcer** [comment]
This is already done with Thinger.io and IFTTT. Works pretty good. But I think a standalone AwtrixApp is nice to have too
